name: Playwright Tests

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install pytest playwright pytest-playwright

      - name: Install Playwright browsers
        run: playwright install --with-deps chromium

      - name: Run tests
        run: pytest ./test_suites --log-cli-level=INFO
